version: "3.7"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306" # Exposed on your host as 3307 because 3306 is usually not vacant
    env_file:
      - sample-mysql.env
    restart: always
    command: --default-authentication-plugin=mysql_native_password
  rchs-local:
    build: ../../
    ports:
      - "8080:8080"
    env_file:
      - sample-combined-compose.env
    environment:
      WAIT_HOSTS: mysql:3306
    restart: on-failure


