version: "3"
services:
  mysql-db:
    build: ./
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    env_file:
      - sample-mysql.env
    restart: always
    command: --default-authentication-plugin=mysql_native_password
